# HTML
- task: rapid7-insightappsec@1
  inputs:
    apiConnection: 'insight appsec'
    application: '776ecf2c-6d80-4d11-8800-e9e665f3a018'
    scanConfig: 'AzureScanConfig'
    generateFindingsReport: true
    publishPipelineArtifacts: true
    artifactPerReport: true
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
